Objetivo 4
LuisSS20/DontWait pull request #17
Opened 2021-12-12 12:07 UTC by LuisSS20

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ]  ¿Se han documentado las elecciones de biblioteca de aserciones y de
   *framework* de test?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?

2021-12-12 19:32 UTC, LuisSS20 commented
@JJ listo para revisión!

2021-12-14 17:48 UTC, LuisSS20 commented
@jj Revisor aleatorio que ha aceptado revisar mi PR @joaquingv12

2021-12-14 19:00 UTC, joaquingv12 requested changes
Te he comentado unos cuantos detalles.

2021-12-14 19:02 UTC, LuisSS20 commented
@Parka015 revisor aleatorio!

2021-12-14 21:12 UTC, LuisSS20 commented on tests/test_colas.py
> +    colas.aniadir_turno('Fruteria')
Gracias por hacérmelo ver!! 😄

2021-12-14 21:13 UTC, LuisSS20 commented on src/colas_disponibles.py
> +        id_nuevo_turno = len(self.colas_disponibles[tipo_cola]) + 1
Es un caso que había tenido en cuenta pero para otra actualización de código, actualmente pienso que no es del todo necesario. Por lo general, las tiendas suelen tener una misma cola para cada sección.

2021-12-14 21:49 UTC, joaquingv12 approved these changes
Por mi parte me parece correcto 👍🏽 .

2021-12-15 22:46 UTC, Parka015 commented on README.md
> +invoke tests
En mi caso, JJ me mencionó escribir "invoke test" en lugar de "invoke tests

2021-12-15 22:51 UTC, Parka015 commented on docs/objetivo-4.md
> +es decir, eficiencia. También busco que sea lo más sencillo posible a la hora de crear
No creo que la rapidez de los tests dependa de la herramienta de test, más bien de la implementación de los mismos. Otra cosa es que, por ejemplo, sea una herramienta fácil de usar y permita el desarrollo rápido de tests

2021-12-15 23:26 UTC, Parka015 commented
Por ultimo comentar:
* Sería buena práctica que los issues perteneciesen a un Milestone
* Como ya sabes, faltaría la tarea de documentar que has seguido los principios FIRST

2021-12-16 11:48 UTC, LuisSS20 commented on README.md
> +invoke tests
Cambiado gracias! :+1:

2021-12-16 11:49 UTC, LuisSS20 commented
> Por ultimo comentar:
> 
>     * Sería buena práctica que los issues perteneciesen a un Milestone
> 
>     * Como ya sabes, faltaría la tarea de documentar que has seguido los principios FIRST

Cambio en el un issue que no estaba asignado a una milestone.
Y tambien he añadido la justificación F.I.R.S.T :+1:

2021-12-16 11:52 UTC, LuisSS20 commented on docs/objetivo-4.md
> +es decir, eficiencia. También busco que sea lo más sencillo posible a la hora de crear
Cuando me estuve informando sobre que herramienta usar para realizar tests con el criterio de la velocidad, ví que la ejecución en PyTest era más rápida que usando otras herramientas. Así que a la hora de ejecutar tests, si influye la herramienta que usas.

2021-12-16 16:18 UTC, JJ commented on docs/objetivo-4.md
> +es decir, eficiencia. También busco que sea lo más sencillo posible a la hora de crear
¿Más rápida que cuales?

2021-12-16 16:26 UTC, JJ requested changes
Principal problema: tienes que crear y testear la lógica de negocio.

2021-12-16 16:26 UTC, JJ commented on README.md
> + invoke check-sintax
typo. Y debe ser solo check, además.

2021-12-16 16:26 UTC, JJ commented on README.md
> +invoke check-good-pratices
???
Se dice best practices, además.

2021-12-16 16:26 UTC, JJ commented on docs/objetivo-4.md
> +Después de investigar por la red que herramientas eran las más populares para poder
No son comparables. Por favor, infórmate bien antes de ponerlas. ¿Escribes unittest y te corre todos los tests igual que pytest?

2021-12-16 16:26 UTC, JJ commented on docs/objetivo-4.md
> +Mirando comparativas que herramienta era la más eficiente, descarté Robot.
... porque ...

2021-12-16 16:26 UTC, JJ commented on docs/objetivo-4.md
> +Con Pytest solo tengo que definir las funciones de test y dentro las aserciones.
Agh, no, esto no es verdad ni por el forro. Ni siquiera son comparables. unittest es una biblioteca de aserciones, pytest un test runner y framework de test que no tiene aserciones (más que tres o cuatro). No son ni comparables.

2021-12-16 16:26 UTC, JJ commented on docs/objetivo-4.md
> +Como opciones tenía assertpy y grappa. Grappa la acabé descartando ya que me informé
¿Y no hay ninguna otra? ¿Como por ejemplo unittest?

2021-12-18 01:10 UTC, LuisSS20 commented
@JJ Ya está listo para revisar de nuevo la lógica de negocio. Cuando pueda, revíselo, gracias!

2021-12-21 10:48 UTC, JJ requested changes
Aparte de los problemas señalados, que no has atendido, el PR not tiene nada que ver con el milestone en el que está, ni "alguna opción" describe un producto mínimamente viable.

2021-12-21 10:48 UTC, JJ commented on README.md
> +invoke check-best-pratices
Typo. Tampoco sé lo que hace ni por qué hace falta.

2021-12-21 10:48 UTC, JJ commented on docs/objetivo-4.md
> +es decir, eficiencia. También busco que sea lo más sencillo posible a la hora de crear
Ping

2021-12-21 10:48 UTC, JJ commented on docs/objetivo-4.md
> +Después de investigar por la red que herramientas eran las más populares para poder
Ping

2021-12-21 10:48 UTC, JJ commented on docs/objetivo-4.md
> +Mirando comparativas que herramienta era la más eficiente, descarté Robot.
Ping

2021-12-21 10:48 UTC, JJ commented on docs/objetivo-4.md
> +Con Pytest solo tengo que definir las funciones de test y dentro las aserciones.
Ping

2021-12-21 10:48 UTC, JJ commented on src/cliente.py
> +    @correo.setter
¿Quién pide este setter?

2021-12-21 10:48 UTC, JJ commented on src/cliente.py
> +            Setter del nombre del cliente
Ese copy/paste...

2021-12-21 10:48 UTC, JJ commented on src/enum_tipo_cola.py
> +    Pescaderia = 1
No tengo muy claro por qué hay que indicar el tipo de cola. ¿Eso afecta a la lógica de negocio?

2021-12-21 10:48 UTC, JJ commented on src/colas_disponibles.py
> +    def calcular_rendimiento_colas(self):
Esto no tiene nada que ver con el módulo en el que está.

2021-12-21 19:50 UTC, LuisSS20 commented on src/cliente.py
> +    @correo.setter
Por ahora nadie, había pensado usarlo en futuras versiones. Si no es necesario ahora mismo debería eliminarlo?

2021-12-21 19:50 UTC, LuisSS20 commented on src/enum_tipo_cola.py
> +    Pescaderia = 1
Lo había pensado de tal manera que al generar las colas de la tienda, se generen automaticamente las especificadas en este enum. Además de ser a la hora de programar, para mí, más intuitivo.

2021-12-21 20:17 UTC, LuisSS20 commented on README.md
> +invoke check-best-pratices
Lo qua hace es checkear las buenas prácticas a la hora de programar en Python. Lo usaba un poco como guía para ver si mi código se adecuaba a estas prácticas.

2021-12-21 20:36 UTC, LuisSS20 commented
@JJ listo para revisión!

2021-12-22 09:01 UTC, JJ commented on src/cliente.py
> +    @correo.setter
¿De veras me tienes que preguntar eso? ¿En qué quedó en hacer sólo el código que corresponda a las HUs que se han creado?

2021-12-22 09:01 UTC, JJ commented on README.md
> +invoke check-best-pratices
Lo que os pedía en el objetivo 3 es un "check" que compilara, que veo que ha desaparecido...

2021-12-22 09:13 UTC, LuisSS20 commented on README.md
> +invoke check-best-pratices
No, no ha desaparecido. Yo tenía un check y un check-good-practices. El check-good-practices lo borré ayer. El check que únicamente compila sigue estando.

2021-12-22 09:17 UTC, JJ requested changes
En general, está bien trabajado, está hecha la lógica de negocio y demás. El problema son los detalles. Otra vuelta y lo tienes.

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +es decir, eficiencia. También busco que sea lo más sencillo posible a la hora de crear
Sabes que los comentarios no son el sitio para argumentar algo, sino el texto en si, ¿no?

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +Después de investigar por la red que herramientas eran las más populares para poder
Efectivamente, no lo entiendes, por eso te digo que no lo entiendes. Conviene que trates de entenderlo, porque aunque estén metidos en el mismo saco, tienen funcionalidades muy diferentes.

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +Mirando comparativas que herramienta era la más eficiente, descarté Robot.
... igual que arriba, las cosas se dicen en el texto, no como contestación a los comentarios. En todo caso, los criterios para elección de la herramienta tienen que ser lo primero, y luego se tiene que decir por qué se ha descartado o elegido una herramienta con respecto a esos criterios.

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +Ya que al investigar, encontré en el siguiente [artículo](https://www.fleekitsolutions.com/pytest-vs-robot-automation-testing/) una mención que dice lo siguiente: "With Pytest, Execution time for tes
... dependerá de lo que testees y del proyecto, y no has probado que en tu proyecto sea más rápido.

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +Después de investigar por la red que herramientas eran las más populares para poder
En todo caso, en el código de arriba tienes varios errores
* Usas dos bibliotecas de aserciones: Unittest (que aparte de tener objetos de tests tiene aserciones) y assertpy. En realidad esta no la usas, porque hasta el IDE te señala algo y será seguramente que no la has usado.
* Ese programa funciona sin pytest, puedes ejecutarlo directamente. Pytest lo que hace es recoger los resultados.
En resumen, trata de entender lo que hace cada herramienta, por favor. Mira la lista de comprobación donde dice "distinguir entre test runner y biblioteca de aserciones"

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +Con Pytest solo tengo que definir las funciones de test y dentro las aserciones.
`pytest` puede usar como aserciones el "assert" que es estándar en Python o cualquier otra biblioteca de aserciones. O sea, no son comparables en absolutamente nada (salvo que pytest tiene unas cuantas aserciones, principalmente para complementar el parco "assert" de Python)

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +Como opciones tenía assertpy y grappa. Grappa la acabé descartando ya que me informé
Ping

2021-12-22 09:17 UTC, JJ commented on docs/objetivo-4.md
> +## Herramienta para tests: PyTest.
"Herramienta" es demasiado genérico.

2021-12-22 09:17 UTC, JJ commented on src/tienda.py
> +            raise TypeError('El cliente no se encuentra entre los \
No tengo muy claro por qué tienes que identificar el cliente. Simplemente se trata de que se sepa cuanto tiene que esperar cada uno. ¿Hace falta que sea cliente de la tienda?

2021-12-22 09:17 UTC, JJ commented on tests/test_clientes.py
> +def test_get_id_turno_cliente(mi_cliente, mi_turno):
¿No deberías de testear más cosas? ¿Como que cambia de turno cuando le toca o algo?

2021-12-22 09:17 UTC, JJ commented on tests/test_colas.py
> +    clientes.append(Cliente('Angel', 'angel@gmail.com', '02/09/1995'))
usa un bucle y un fichero de texto.

2021-12-22 09:17 UTC, JJ commented on tests/test_colas.py
> +        sleep(random.uniform(0, 0.004))
No puedes simular tiempo real en el test, entre otras cosas porque introduce retrasos que no sirven de nada. ¿No puedes simplemente generar tiempos aleatorios?

2021-12-22 09:17 UTC, JJ commented on src/colas_disponibles.py
> +        tiempo_final = time.time()
El "reloj" deberías inyectarlo. Si no te vas a ver obligado a usar tiempo real para los tests, y no puedes simular cosas como que espere una hora o lo que sea. Simplemente crea un objeto "mytime", que use o tiempo real en producción o tiempo simulado en tests. Para eso sirve la inyección de dependencias (y puse este mismo ejemplo en clase, creo recordar)

2021-12-22 14:35 UTC, LuisSS20 reviewed
@JJ Listo para revisión! Espero haber solucionado ya los problemas que tenía :+1:

2021-12-22 14:35 UTC, LuisSS20 commented on tests/test_clientes.py
> +def test_get_id_turno_cliente(mi_cliente, mi_turno):
Acabo de crear un nuevo test, que una vez atendido el turno del cliente este sea un objeto nulo, es decir, no tenga un turno asociado.

2021-12-22 16:41 UTC, JJ requested changes
Una vuelta más, por favor.

2021-12-22 16:41 UTC, JJ commented on docs/objetivo-4.md
> +Después de investigar por la red que herramientas eran las más populares para poder
Sigues sin entender lo que estás usando. Cuando haces un caso de test que hereda de UnitTest.TestCase, el `self` que estás usando para `self.asserTrue` *es de UnitTest*. UnitTest es una biblioteca de aserciones, y lo puedes llamar *framework* o lo que te dé la gana, pero esencialmente lo que tiene es aserciones (a través de un interfaz OO). `pytest` es un test runner que tiene algunas aserciones, porque es compatible con cualquiera d eellos. ¿Por qué? Porque es un test runner, y lo que hace es crear un entorno de paths (¿por qué hay programas que funcionan sólo cuando los corres desde `pytest`?), buscar los ficheros de test (sólo hay que ejecutar pytest) y además interpretar la salida de los ficheros (que usan el protocolo que usan todos los tests runners, TAP, *que expliqué en clase repetidamente*). ¿Es un "framework" de test? Sí, porque hace "cosas de test". ¿Lo es también UnitTest? Sí, porque también hace "cosas de tests". ¿Son comparables en el sentido de "Sí, voy a dejar el pytest este y me voy a poner a usar UnitTest"? No, ni de lejos.
Y ese es precisamente el tema. tienes que entender exactamente qué es un test runner, qué es una biblioteca de aserciones, y no repetir lo que dice en no sé qué artículo. Y parafraseando a Groucho, "¿me vas a creer a mi o a tus propios ojos?". En realidad, es a *tu propio código*, donde estás usando  UnitTest como biblioteca de aserciones, en contradicción, aparentemente, de lo que dice en ese documento en internet.

2021-12-22 16:41 UTC, JJ commented on docs/objetivo-4.md
> +Mirando comparativas que herramienta era la más eficiente, descarté Robot.
¿Cuesta mucho trabajo decir descarté Robot *por el criterio X que he establecido de antemano*?

2021-12-22 16:41 UTC, JJ commented on docs/objetivo-4.md
> +Con Pytest solo tengo que definir las funciones de test y dentro las aserciones.
Y yo sigo diciendo lo mismo, estás equivocado y no estás enendiendo lo que es una aserción ni lo que es un test runner.

2021-12-22 16:41 UTC, JJ commented on src/cliente.py
> +    @correo.setter
No, no lo está, y tampoco es necesario para nada. ¿Va a cambiar el correo una vez establecido? ¿Hace falta el correo para qué exactamente de la lógica de negocio?

2021-12-22 16:41 UTC, JJ commented on src/turno.py
> +            Getter del id del turno.
¿hace falta por qué?

2021-12-22 16:41 UTC, JJ commented on src/turno.py
> +    @id.setter
¿En serio que puede cambiar el ID? ¿Qué pasa entonces con todos los que se refieran a este ID?
De veras que el tema de getters y setters tenéis que mirarlo. Pista: en general no hacen falta ninguno de los dos, porque son detalles de implementación que no tienen por qué salir de la clase.

2021-12-22 16:41 UTC, JJ commented on tests/test_colas.py
> +    mi_tienda._servicios.comienzo_atender_turno(mi_tienda._servicios.colas_disponibles['Pescaderia'], 0)
¿Vas a comprobar código diferente si añades Pescadería o Frutería? Los tests deben hacerse no "porque hay que hacer test" sino porque quieres que actúen diferentes partes del código.

2021-12-22 16:41 UTC, JJ commented on tests/test_colas.py
> +    for i in range(2):
DRY: evitar código repetido.

2021-12-22 16:41 UTC, JJ commented on tests/test_colas.py
> +        mi_tienda._servicios.termino_atender_turno(mi_tienda._servicios.colas_disponibles['Fruteria'], 40)
De hecho, como digo arriba, sólo añade más código que no testea ninguna funcionalidad nueva.

2021-12-22 18:54 UTC, LuisSS20 commented
@JJ listo para revisión.

2021-12-23 11:28 UTC, JJ approved these changes
Sigues escribiendo una cantidad de tests que no prueban código nuevo, y sigues teniendo una cantidad de código considerable que no sirve a la lógica de negocio. No voy a mantenerte más tiempo en este objetivo por eso, pero espero que lo corrijas antes del siguiente objetivo.

2021-12-23 11:28 UTC, JJ commented on src/cliente.py
> +        self._correo = correo
De veras que no entiendo por qué necesitas el email de una criatura para decirle que tiene que esperar 20 minutos en la cola. Si quieres identificarlo de modo único, simplemente asígnale un ID. ¿Dónde en la lógica de negocio usas el email? ¿le vas a mandar un email cuando le toque? Por favor, aprended a no hacer cosas innecesarias en el código...

2021-12-23 11:28 UTC, JJ commented on src/cliente.py
> +        self._fechaNac = fechaNac
Si el email es (posiblemente) inútil, no te digo nada la fecha de nacimiento...

2021-12-23 11:28 UTC, JJ commented on src/cliente.py
> +        return self._nombre
¿Lo vas a llamar por nombre cuando le toque en la cola?

2021-12-23 11:28 UTC, JJ commented on src/cliente.py
> +    def nombre(self, nom):
¿Si a mitad de hacer cola cambia de nombre, vas a cambiarle el nombre?

2022-01-02 13:47 UTC, merged