Objetivo 5
LuisSS20/DontWait pull request #24
Opened 2022-01-05 16:35 UTC by LuisSS20

* [ ]  ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ]  ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests?
* [ ]  ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ]  ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ]  ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello?

2022-01-05 17:22 UTC, JJ commented
⛹ Revisores → @Antobio17 @amerigal @danifm1321

2022-01-05 19:51 UTC, noise-kngdm requested changes
Lo que es el código en sí lo veo bien, pero creo que deberías considerar más criterios a la hora de elegir el contenedor base, además de usar uno con la última versión LTS de Debian, no con la anterior. También te he pedido algunos relacionados con buenas prácticas.
También estarí bien que pusieras en el archivo `tasks.py` una task para lanzar el contenedor y correr los tests que se lanzara como `inv docker` o algo así.

2022-01-05 19:51 UTC, noise-kngdm commented on Dockerfile
> +ENTRYPOINT ["invoke", "test"]
Falta un salto de línea al final del archivo.

2022-01-05 19:51 UTC, noise-kngdm commented on .github/workflows/upload_dockerhub.yml
> +          tags: latest
Falta un salto de línea al final del archivo. Es buena práctica y que muchos programas UNIX lo dan por hecho, ya que es parte de cómo [POSIX defined una línea](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

2022-01-05 19:51 UTC, noise-kngdm commented on docs/objetivo-5.md
> +Primero intenté usar imágenes de una distribución oficial, ubuntu 18.04 y debian. Al usar esta opción tenemos que instalar python3.9 en el dockerfile. Sin embargo el tamaño de estos contenedores eran
Creo que estaría bien si pusieras algún ejemplo del tamaño de un contenedor basado en esas imágenes también.

2022-01-05 19:51 UTC, noise-kngdm commented on docs/objetivo-5.md
> +Al comprobar que la imagen de alpine ocupaba el doble, la descarté y opté por usar slim-buster.
Creo que estaría bien comparar no solo el tamaño de las imágenes, si no también cuánto tarda en buildearse cada contenedor y una comparación de rendimiento, por ejemplo lo que tardaría cada contenedor en correr los tests.

2022-01-05 19:51 UTC, noise-kngdm commented on docs/objetivo-5.md
> +1. 3.9-slim-buster: Esta imagen contiene los paquetes mínimos necesarios para ejecutar python, por lo tanto es ideal.
Creo que en vez de `3.9-slim-buster` podrías haber usado `3.9-slim-bullseye`, ya que buster es la antigua versión LTS de debian y bullseye la actual según la [documentación de Debian].

2022-01-05 19:51 UTC, noise-kngdm commented on docs/objetivo-5.md
> +Se necesitara un contenedor que pueda ejecutar código de python y que sea de tamaño reducido, ya que su funcionalidad es la ejecución de los tests desarrollados anteriormente.
Creo que deberías añadir más requisitos en tu elección de la imagen base. Si tuvieras una imagen de 10MB con Python que tardara dos días en ejecutar tu código la elegirías antes que una de 100MB que tardara 0.1 segundos? Según los actuales requisitos sí, pero sabemos que no sería una buena decisión.

2022-01-05 19:51 UTC, noise-kngdm commented on docs/objetivo-5.md
> +3. 3.9-alpine: Es la imagen más recomendada para no tener problemas de espacio, sin embargo puede causar problemas de compatibilidad (en mi caso me dió un problema al intentar instalar poetry, lo arr
Sugiero que podrías poner información acerca del error que tuviste que arreglar y cómo lo hiciste.

2022-01-05 19:51 UTC, noise-kngdm commented on docs/objetivo-5.md
> +Para que el build funcione correctamente se debe usar esta opción para que poetry NO instale las dependencias en su entorno virtual.
Creo que esta justificación no está del todo bien. Si tú no tuvieras esta línea en tu Dockerfile podrías cambiar el entrypoint por `poetry run invoke test` y funcionaría (lo he probado en local clonando tu repo).

Me parece bien que tengas esa línea, pero creo que la razón sería más bien que no es necesario crear nuevos entornos virtuales para un contenedor que se va a dedicar a ejecutar una sola aplicación.

2022-01-05 22:23 UTC, LuisSS20 commented on docs/objetivo-5.md
> +1. 3.9-slim-buster: Esta imagen contiene los paquetes mínimos necesarios para ejecutar python, por lo tanto es ideal.
Tienes razón, lo he consultado y he cambiado la imagen, gracias!!

2022-01-05 22:23 UTC, LuisSS20 commented on docs/objetivo-5.md
> +Al comprobar que la imagen de alpine ocupaba el doble, la descarté y opté por usar slim-buster.
hecho!

2022-01-06 12:09 UTC, noise-kngdm requested changes
Lo veo bastante mejor que la anterior versión, buen trabajo. Te he vuelto a pedir como sugerencia que pongas un ejemplo del tamaño final de la imagen si usaras una imagen base más de 'propósito general' (un debian, centos o ubuntu por ejemplo), lo dejo a tu elección.
También creo que deberías revisar el párrafo en el que explicas por qué has deshabilitado la opción `virtualenvs.create` de Poetry, ya que das a entender que si no la usaras el contenedor no funcionaría, cuando ya te puse en la anterior revisión que si cambiaras el entrypoint funcionaría también.

2022-01-06 12:09 UTC, noise-kngdm commented on docs/objetivo-5.md
> +Para que el build funcione correctamente se debe usar esta opción para que poetry NO instale las dependencias en su entorno virtual, ya que no necesitamos nuevos entornos virtuales en este contenedor
La build funcionaría correctamente sin tener que usar esa opción si configuras el entrypoint como dije en el anterior comentario.
```suggestion
He usado esta opción para que poetry no instale las dependencias en un nuevo entorno virtual, ya que no necesitamos varios entornos virtuales en este contenedor que ejecuta una sola aplicación.
```

2022-01-06 12:09 UTC, noise-kngdm commented on docs/objetivo-5.md
> +Primero intenté usar imágenes de una distribución oficial, ubuntu 18.04 y debian. Al usar esta opción tenemos que instalar python3.9 en el dockerfile. Sin embargo el tamaño de estos contenedores eran
@LuisSS20 sigo pensando que no estaría de más hacer esto.

2022-01-06 12:26 UTC, danifm1321 requested changes
He propuesto un único cambio con respecto a los requisitos usados para la elección de la imagen.

2022-01-06 12:26 UTC, danifm1321 commented on docs/objetivo-5.md
> +Se necesitara un contenedor que pueda ejecutar código de python, que sea de tamaño reducido, que no tarde mucho en construirse y que ejecute rápidamente los tests.
El tiempo de ejecución de los tests es independiente a la imagen de docker que utilices, ¿no? La imagen de docker influye en la construcción del propio docker, pero ya lo que pase dentro es cosa de tu código.

2022-01-06 12:36 UTC, noise-kngdm commented on docs/objetivo-5.md
> +Se necesitara un contenedor que pueda ejecutar código de python, que sea de tamaño reducido, que no tarde mucho en construirse y que ejecute rápidamente los tests.
No tiene por qué, una imagen podría tener versiones más actualizadas de librerías que use el proyecto que otra, lo cual podría incurrir en diferencias de rendimiento. Además, diferentes sistemas operativos no tienen por qué rendir igual ya que van a utilizar diferentes herramientas, lo cual podría también afectar a lo que tarda la aplicación en ejecutarse.

2022-01-06 12:36 UTC, JJ commented on docs/objetivo-5.md
> +Se necesitara un contenedor que pueda ejecutar código de python, que sea de tamaño reducido, que no tarde mucho en construirse y que ejecute rápidamente los tests.
No tiene por qué. Pueden ir más rápidamente o menos dependiendo del núcleo, de la biblioteca estándar que usen, y demás.

2022-01-06 12:44 UTC, danifm1321 commented on docs/objetivo-5.md
> +Se necesitara un contenedor que pueda ejecutar código de python, que sea de tamaño reducido, que no tarde mucho en construirse y que ejecute rápidamente los tests.
Entiendo, he buscado un poco antes de poner mi comentario pero no he encontrado nada concluyente, nunca esta de mal saberlo.

2022-01-06 13:29 UTC, LuisSS20 commented
@noise-kngdm listo para revision! :smile:

2022-01-06 13:42 UTC, noise-kngdm approved these changes
Lo veo mucho mejor, buen trabajo!

2022-01-06 20:14 UTC, Antobio17 reviewed
Acabo de revisar y lo veo muy completo! Buen trabajo :+1: 
Sobre todo la documentación, ya que se basa en las pruebas de varias imágenes base para realizar una elección con fundamente.
Comentarte que según aprendí yo en mi objetivo 5 el requisito del **tiempo de ejecución de los tests** debería ser el que mande (a parte de la ejecución de código Python como es normal) a la hora de elegir la imagen.

2022-01-07 12:50 UTC, LuisSS20 commented
@JJ listo para revisión! :smile:

2022-01-07 19:13 UTC, JJ approved these changes
Esencialmente se han alcanzado los objetivos, aunque deberías de tener algo de más cuidado en los objetivos y en la justificación. Por favor, mira también bien qu ese sigan las mejores prácticas en el desarrollo.

2022-01-07 19:13 UTC, JJ commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py ./
Este directorio no debe ser a donde se copien las cosas, porque se va a pisar. En todo caso, debes borrarlas cuando las uses.

2022-01-07 19:13 UTC, JJ commented on docs/objetivo-5.md
> +Debian          ->     REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
No son las únicas. También está Debian slim. O Fedora, yo qué sé.

2022-01-07 19:13 UTC, JJ commented on docs/objetivo-5.md
> +Asi que decidí buscar entre las imagenes oficiales del lenguaje Python.
No hay ninguna razón para que no consideres también las de bitnami, por ejemplo.

2022-01-08 19:19 UTC, merged