Objetivo 3
LuisSS20/DontWait pull request #9
Opened 2021-11-23 21:55 UTC by LuisSS20

2021-12-01 08:11 UTC, JJ requested changes
Ningún commit se refiere a ningún issue. Incluso en código de infraestructura debe haber uno. En general, sígase la lista de comprobación del objetivo correspondiente.
El Milestone tampoco tiene nada que ver con lo que aquí hay, ni incluye esto como PMV.

2021-12-01 08:12 UTC, JJ commented
Tampoco has hecho un PR.

2021-12-03 08:50 UTC, JJ requested changes
Dale una vueltecilla, si quieres sobre la marcha y lo vemos antes del final de la clase.

2021-12-03 08:50 UTC, JJ commented on README.md
> +Para poder probarlo, primero tenemos que activar el entorno virtual haciendo uso de:
Esto no hace falta. Además, es estándar. Si vais a repetir cosas del manual de una herramienta, simplemente apuntad al manual.

2021-12-03 08:50 UTC, JJ commented on docs/objetivo-3.md
> +## Gestor de tareas elegido: Invoke.
Empiezas por la elección, y debes empezar *siempre* por los criterios para elegir. Usa la lista de comprobación del objetivo, y ponla en el PR.

2021-12-03 08:50 UTC, JJ commented on src/cliente.py
> +    # Clase cliente
Si vas a poner documentación, usa docstrings. Y si vas a poner lo mismo que pone en el código, no pongas nada.

2021-12-03 08:50 UTC, JJ commented on tasks.py
> +    c.run("pylint src")
¿Por qué usas pylint? ¿Quién ha dicho que lo uséis? pylint es un comprobador estático de código y buenas prácticas, no un comprobador de sintaxis.

2021-12-05 11:59 UTC, LuisSS20 commented
@JJ listo para revisión!

2021-12-07 11:35 UTC, JJ approved these changes
:+1: pero en el futuro trata de hacer mejor las justificaciones.

2021-12-07 11:35 UTC, JJ commented on docs/objetivo-3.md
> +Y entre Pypyr e Invoke, decidí Invoke porque me parecía más cómodo.
O sea, ninguno de los tres criterios que has puesto arriba.

2021-12-07 11:35 UTC, JJ commented on README.md
> +```
Aquí sigue...

2021-12-07 15:38 UTC, merged